### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by knivit** [ceylon/ceylon-runtime#83]
$ uname
CYGWIN_NT-6.3
$ ceylon --help
Error: Unable to access jarfile /home/user/programs/ceylon-1.2.0/bin/../lib/ceylon-bootstrap.jar

For myself, I've modified bin/ceylon the next way:
LIB=\`cygpath --path --windows $LIB\`
exec "$JAVA" \
 $JAVA_OPTS \
 -jar "$LIB/ceylon-bootstrap.jar" \
 "$@"

A complete fix may be like Apache Maven's bin/mvn
Thanks

**Comment by gavinking** [comment]
This bug probably belongs in `ceylon-dist` or something. WDYT, @quintesse @FroMage ?

**Comment by FroMage** [comment]
In ceylon-common ATM :(

**Comment by FroMage** [comment]
Moved to https://github.com/ceylon/ceylon-common/issues/65
